- name: Instala los paquetes necesarios
  apt:
    pkg:
      - isc-dhcp-server
      - iptables
    
- name: Copiar el /etc/dhcp/dhcpd.conf - Plantilla
  template:
    src: dhcpd.conf
    dest: /etc/dhcp/dhcpd.conf
    owner: root
    group: root
    mode: 0644

- name: Copiar el /etc/default/isc-dhcp-server - Plantilla
  template:
    src: isc-dhcp-server
    dest: /etc/default/isc-dhcp-server
    owner: root
    group: root
    mode: 0644
